update dist

diff --git a/dist/install b/dist/install
--- a/dist/install
+++ b/dist/install
@@ -16,18 +16,13 @@ init () {
 
 autoPartition () {
     parted $1 --script mklabel msdos \
-           mkpart primary ext4 3MiB 512MiB \
-           set 1 boot on \
-           mkpart primary ext4 512MiB 100% 2> /tmp/err || errorDialog "Failed to create disk partitions"
+           mkpart primary ext4 3MiB 100% \
+           set 1 boot on 2> /tmp/err || errorDialog "Failed to create disk partitions"
 
     yes | mkfs.ext4 "${1}1" > /dev/null 2> /tmp/err || error "Failed to format the boot partition"
     yes | mkfs.ext4 "${1}2" > /dev/null 2> /tmp/err || error "Failed to format the root partition"
 
-    mount "${1}2" /mnt
-    mkdir /mnt/boot
-    mount "${1}1" /mnt/boot
-
-    setvar "boot-partition" "${1}1"
+    mount "${1}1" /mnt
     setvar "system-partition" "${1}2"
 }
 
@@ -35,8 +30,8 @@ installCoreSystem () {
     getvar "system-partition"
     systempt=$value
 
-    getvar "boot-partition"
-    bootpt=$value
+    getvar "disk"
+    disk=$value
 
     pacstrap /mnt base
     genfstab -U /mnt >> /mnt/etc/fstab
@@ -44,18 +39,16 @@ installCoreSystem () {
     arch-chroot /mnt <<EOF
 mkdir -p /usr/local/installer && cd /usr/local/installer
 curl -L $DISTRO_DL > ./install
-echo -e "system-partition=$systempt\nboot-partition=$bootpt\ncore-install-step=done\npartition-step=done" > ./install-vars
+echo -e "system-partition=$systempt\ndisk=$disk\ncore-install-step=done\npartition-step=done" > ./install-vars
 chmod +x ./install
 pacman -S --noconfirm dialog
 ./install continue
-EOF
+ EOF
 }
 
 installGRUB () {
-    pacman -S --noconfirm g
-
-    rub 2> /tmp/err || errorDialog "Failed to install GRUB"
-    getvar "boot-partition"
+    pacman -S --noconfirm grub 2> /tmp/err || errorDialog "Failed to install GRUB"
+    getvar "disk"
     grub-install --target=i386-pc --recheck $value 2> /tmp/err || errorDialog "Failed to install GRUB"
 }
 
@@ -262,6 +255,7 @@ diskMenu () {
                       15 30 30 \
                       "${disksArray[@]}")
 
+    setvar "disk" "$selected"
     selected=$(lsblk -r | grep disk | cut -d" " -f1 | sed -n "${selected}p")
     selected="/dev/${selected}"
 }
@@ -287,20 +281,16 @@ partitionSelectionForm () {
                     --nocancel \
 	                  --form "" \
                     7 50 0 \
-	                  "/boot" 1 1	"${1}1" 	1 10 45 0 \
-	                  "/"    2 1	"${1}1"  	2 10 45 0)
+	                  "Root: "    2 1	"${1}1"  	2 10 45 0)
 
-    bootpt=$(echo "$values" | head -n1)
     systempt=$(echo "$values" | tail -n1)
 
-    if [[ (-z "${bootpt// }") || (-z "${systempt// }") ]]; then
-        echo "bad input $bootpt and $systempt"
-        dialog --title "Select Partitions" \
+    if [[ -z "${systempt// }" ]]; then
+        dialog --title "Select System Partition" \
                --backtitle "Happy Hacking Linux" \
-               --msgbox "You need to fill both fields" 6 50
-        partitionForm
+               --msgbox "Sorry, you have to choose the partition you'd like to install the system." 6 50
+        partitionSelectionForm
     else
-        setvar "boot-partition" $bootpt
         setvar "system-partition" $systempt
     fi
 }
