Format the partition as ext4 before mounting

diff --git a/dist/install b/dist/install
--- a/dist/install
+++ b/dist/install
@@ -395,11 +395,9 @@ partitionSelectionForm () {
 	                  --title "Select Partitions" \
                     --nocancel \
 	                  --form "" \
-                    10 50 0 \
-	                  "Boot Mount: "    2 1	"${1}1"  	2 15 45 0 \
-			  "System Mount: "    3 1	"${1}1"  	3 15 45 0)
+                    7 50 0 \
+	                  "Root Mount: "    2 1	"${1}1"  	2 15 45 0)
 
-    mountpt=$(echo "$values" | tail -n2 | head -n1)
     systempt=$(echo "$values" | tail -n1)
 
     if [[ -z "${systempt// }" ]]; then
@@ -408,7 +406,8 @@ partitionSelectionForm () {
                --msgbox "Sorry, you have to choose the partition you'd like to install the system." 6 50
         partitionSelectionForm
     else
-        mount $mountpt /mnt
+        yes | mkfs.ext4 $systempt > /dev/null 2> /tmp/err || error "Failed to format the root partition"
+        mount $systempt /mnt
         setvar "system-partition" $systempt
     fi
 }
