optimize installation steps

diff --git a/dist/install b/dist/install
--- a/dist/install
+++ b/dist/install
@@ -181,7 +181,8 @@ installDefaultDotFiles () {
 
 installZSH () {
     pacman --noconfirm -S zsh > /dev/null 2> /tmp/err || errorDialog "Can not install ZSH. Are you connected to internet?"
-    chsh -s $(which zsh) > /dev/null 2> /tmp/err || errorDialog "Something got screwed up, we can't change the default shell to ZSH."
+    chsh -s $(which zsh) > /dev/null 2> /tmp/err || errorDialog "Something got screwed up, we can't change the default root shell to ZSH."
+    runAsUser "chsh -s $(which zsh)" > /dev/null 2> /tmp/err || errorDialog "Something got screwed up, we couldn't change your default shell to ZSH."
 }
 
 installOhMyZSH () {
@@ -197,7 +198,6 @@ installVirtualBox () {
 }
 
 installBasicPackages () {
-    pacman --noconfirm -Syu > /dev/null 2> /tmp/err || errorDialog "Failed to install some basic packages."
     pacman -S --noconfirm \
            base-devel \
            net-tools \
@@ -206,13 +206,17 @@ installBasicPackages () {
            openssh \
            wget \
            git \
-           reflector \
            grep 2> /tmp/err || errorDialog "Failed to install basic packages. Check your internet connection please."
 
     installZSH
 }
 
+upgrade () {
+    pacman --noconfirm -Syu > /dev/null 2> /tmp/err || errorDialog "Failed to upgrade the system. Make sure being connected to internet."
+}
+
 findBestMirrors () {
+    pacman -S --noconfirm reflector 2> /tmp/err || errorDialog "Failed to install reflector, are you connected to internet?"
     reflector --latest 200 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist > /dev/null 2> /tmp/err || errorDialog "Something got screwed up and we couldn't accomplish finding some fast and up-to-date servers :("
 }
 
@@ -545,7 +549,7 @@ findBestMirrorsStep () {
 
     dialog --infobox "Looking for faster and more up-to-date mirrors for rest of the installation..." 6 50; findBestMirrors
 
-    setvar "find-best-mirrors-step"
+    setvar "find-best-mirrors-step" "done"
 }
 
 installBasicPackagesStep () {
@@ -554,9 +558,20 @@ installBasicPackagesStep () {
         return
     fi
 
-    dialog --infobox "Installing some basic packages before creating users..." 5 50; installBasicPackages
+    dialog --infobox "Installing some basic packages..." 5 50; installBasicPackages
 
-    setvar "install-basic-packages-step"
+    setvar "install-basic-packages-step" "done"
+}
+
+upgradeStep () {
+    getvar "upgrade-step"
+    if [ "$value" == "done" ]; then
+        return
+    fi
+
+    dialog --infobox "Upgrading the system..." 5 50; upgrade
+
+    setvar "upgrade-step" "done"
 }
 
 installPackagesStep () {
@@ -565,6 +580,10 @@ installPackagesStep () {
         localizeStep
         return
     fi
+
+    upgradeStep
+    findBestMirrorsStep
+    installBasicPackagesStep
 
     installYaourtStep
 
@@ -611,9 +630,6 @@ usersStep () {
 
   getvar "username"
   username=$value
-
-  installBasicPackagesStep
-  findBestMirrorsStep
 
   createUser $username $password
 
