mark done steps as done and avoid duplicating

diff --git a/dist/install b/dist/install
--- a/dist/install
+++ b/dist/install
@@ -20,8 +20,8 @@ autoPartition () {
            set 1 boot on \
            mkpart primary ext4 512MiB 100% 2> /tmp/err || errorDialog "Failed to create disk partitions"
 
-    yes | mkfs.ext4 "${1}1" > /dev/null 2> /tmp/error || error "Failed to format the boot partition"
-    yes | mkfs.ext4 "${1}2" > /dev/null 2> /tmp/error || error "Failed to format the root partition"
+    yes | mkfs.ext4 "${1}1" > /dev/null 2> /tmp/err || error "Failed to format the boot partition"
+    yes | mkfs.ext4 "${1}2" > /dev/null 2> /tmp/err || error "Failed to format the root partition"
 
     mount "${1}2" /mnt
     mkdir /mnt/boot
@@ -44,7 +44,7 @@ installCoreSystem () {
     arch-chroot /mnt <<EOF
 mkdir -p /usr/local/installer && cd /usr/local/installer
 curl -L $DISTRO_DL > ./install
-echo "system-partition=$systempt\nboot-partition=$bootpt"
+echo "system-partition=$systempt\nboot-partition=$bootpt\ncore-install-step=done\npartition-step=done" > ./install-vars
 chmod +x ./install
 pacman -Sy --noconfirm dialog
 ./install continue
@@ -58,10 +58,10 @@ installGRUB () {
 }
 
 localize () {
-    tzselect 2> /tmp/error || errorDialog "tzselect is missing"
+    tzselect 2> /tmp/err || errorDialog "tzselect is missing"
     hwclock --systohc
     sed -i -e '/^#en_US/s/^#//' /etc/locale.gen # uncomment lines starting with #en_US
-    locale-gen 2> /tmp/error || errorDialog "locale-gen is missing"
+    locale-gen 2> /tmp/err || errorDialog "locale-gen is missing"
 
     # FIX ME: Allow user to choose language and keyboard
     echo "LANG=en_US.UTF-8" >> /etc/locale.conf
@@ -170,6 +170,8 @@ installExtraPackages () {
            htop \
            go 2> /tmp/err || errorDialog "Failed to complete installing extra packages"
 }
+CHECK=✔
+
 welcomeMenu () {
     dialog --title "=^.^=" \
            --backtitle "Happy Hacking Linux" \
@@ -182,17 +184,48 @@ welcomeMenu () {
 }
 
 mainMenu () {
+    icon1=""
+    icon2=""
+    icon3=""
+    icon4=""
+    icon5=""
+
+    getvar "partition-step"
+    if [ "$value" = "done" ]; then
+        icon1="${CHECK} "
+    fi
+
+    getvar "core-install-step"
+    if [ "$value" = "done" ]; then
+        icon2="${CHECK} "
+    fi
+
+    getvar "boot-install-step"
+    if [ "$value" = "done" ]; then
+        icon3="${CHECK} "
+    fi
+
+    getvar "localization-step"
+    if [ "$value" = "done" ]; then
+        icon4="${CHECK} "
+    fi
+
+    getvar "users-step"
+    if [ "$value" = "done" ]; then
+        icon5="${CHECK} "
+    fi
+
     selected=$(dialog --stdout \
                       --title "=^.^=" \
                       --backtitle "Happy Hacking Linux" \
                       --ok-label "Select" \
                       --nocancel \
                       --menu "Complete the following installation steps one by one." 16 55 8 \
-                      1 "Setup Disk Partitions" \
-                      2 "Install Core Packages" \
-                      3 "Install Boot (GRUB)" \
-                      4 "Localization" \
-                      5 "Users" \
+                      1 "${icon1}Setup Disk Partitions" \
+                      2 "${icon2}Install Core Packages" \
+                      3 "${icon3}Install Boot (GRUB)" \
+                      4 "${icon4}Localization" \
+                      5 "${icon5}Users" \
                       6 "Install Extras" \
                       7 "Reboot")
 }
@@ -318,6 +351,9 @@ passwordDialog () {
 }
 
 errorDialog () {
+    echo "$1\n\n" > ./install-errors.log
+    [[ -f ~/tmp/err ]] && cat /tmp/err >> ./install-errors.log
+
     echo "Message: $1\nOutput: \n" | cat - /tmp/err > /tmp/err.bak && mv /tmp/err.bak /tmp/err
 
     dialog --title "Oops, there was an error" \
@@ -430,27 +466,46 @@ rebootStep () {
 }
 
 usersStep () {
-  usernameDialog
-  setvar "username" $username
+  getvar "users-step"
+  if [ "$value" != "done" ]; then
+      usernameDialog
+      setvar "username" $username
 
-  passwordDialog
-  createUser $username $password
+      passwordDialog
+      createUser $username $password
+
+      setvar "users-step" "done"
+  fi
 
   mainMenuStep
 }
 
 localizationStep () {
-    localize
+    getvar "localization-step"
+    if [ "$value" != "done" ]; then
+        localize
+        setvar "localization-step" "done"
+    fi
+
     usersStep
 }
 
 installBootStep () {
-    dialog --infobox "Installing GRUB for /boot" 10 50; installGRUB
+    getvar "boot-install-step"
+    if [ "$value" != "done" ]; then
+        dialog --infobox "Installing GRUB for /boot" 10 50; installGRUB
+        setvar "boot-install-step" "done"
+    fi
+
     localizationStep
 }
 
 switchToLTSStep () {
-    dialog --infobox "Switching to Linux LTS Kernel as it's more stable." 10 50; installLTSKernel
+    getvar "lts-step"
+    if [ "$value" != "done" ]; then
+        dialog --infobox "Switching to Linux LTS Kernel as it's more stable." 10 50; installLTSKernel
+        setvar "lts-step" "done"
+    fi
 }
 
 installExtraPackagesStep () {
@@ -458,7 +513,13 @@ installExtraPackagesStep () {
 }
 
 coreInstallStep () {
-    dialog --infobox "Installing core system packages, please wait..." 10 50; installCoreSystem
+    getvar "core-install-step"
+    if [ "$value" != "done" ]; then
+        dialog --infobox "Installing core system packages, please wait..." 10 50; installCoreSystem
+        setvar "core-install-step" "done"
+    fi
+
+    afterCoreInstallStep
 }
 
 afterCoreInstallStep () {
@@ -490,6 +551,7 @@ partitionStep () {
         mainMenuStep
     fi
 
+    setvar "partition-step" "done"
     coreInstallStep
 }
 
