switch to new tty after chroot

diff --git a/dist/install b/dist/install
--- a/dist/install
+++ b/dist/install
@@ -8,6 +8,8 @@ setvar () {
 getvar () {
     value=$(grep "^$1=" ./install-vars | tail -n 1 | sed "s/^$1=//")
 }
+DISTRO_DL="https://git.io/vXbTE"
+
 autoPartition () {
     parted /dev/sda --script mklabel msdos \
            mkpart primary ext4 0% 100% \
@@ -18,10 +20,19 @@ autoPartition () {
 installCoreSystem () {
     getvar "system-partition"
     mount $value /mnt
-    pacstrap /mnt base 2> /tmp/err || errorDialog "Installing core packages failed. Return to main menu and try installing this step again."
+    pacstrap /mnt base
     genfstab -U /mnt >> /mnt/etc/fstab
-    arch-chroot /mnt
-    pacman --noconfirm -Sy dialog > /dev/null
+
+    mkdir /mnt/usr/local/installer
+    curl -L $DISTRO_DL > /mnt/usr/local/installer/install
+    chmod +x /mnt/usr/local/installer/install.sh
+    cp ./install-vars /mnt/usr/local/installer/.
+
+    arch-chroot /mnt <<EOF
+pacman -Sy --noconfirm dialog
+cd /usr/local/installer
+./install
+EOF
 }
 
 installGRUB () {
@@ -143,8 +154,6 @@ v         moc \
          htop \
          go 2> /tmp/err || errorDialog "Failed to complete installing extra packages"
 }
-source ./vars.sh
-
 welcomeMenu () {
 g    dialog --title "=^.^=" \
            --backtitle "Happy Hacking Linux" \
@@ -293,6 +302,8 @@ dotFilesDialog () {
                           --ok-label "Clone & Link All" \
                           --inputbox "Where is your dotfiles located?" 8 50 "git@github.com:"$username"/dotfiles.git")
 }
+command=$1
+
 mainMenuStep () {
     mainMenu
 
@@ -353,7 +364,7 @@ installVimrc () {
 }
 
 installSpacemacs () {
-    dialog --infobox "Installing spacemacs" 10 50; installZSH
+    dialog --infobox "Installing spacemacs" 10 50; installSpacemacs
     extrasMenuStep
 }
 
@@ -422,6 +433,7 @@ partitionStep () {
 
     if [ "$selected" = "1" ]; then
         autoPartition
+        mkfs.ext4 /dev/sda1 > /dev/null 2> /tmp/error || error "Failed to format the disk"
         setvar "boot-partition" "/dev/sda1"
         setvar "system-partition" "/dev/sda1"
     elif [ "$selected" = "2" ]; then
