update mirrors before downloading stuff

diff --git a/dist/install b/dist/install
--- a/dist/install
+++ b/dist/install
@@ -116,10 +116,10 @@ installCoreSystem () {
     pacstrap /mnt base
     genfstab -U /mnt >> /mnt/etc/fstab
 
+    setvar "core-install-step" "done"
+
     mkdir -p /mnt/usr/local/installer
     cp install-vars /mnt/usr/local/installer/.
-
-    setvar "core-install-step" "done"
 
     arch-chroot /mnt <<EOF
 cd /usr/local/installer
@@ -206,9 +206,14 @@ installBasicPackages () {
            openssh \
            wget \
            git \
-           grep  > /dev/null 2> /tmp/err || errorDialog "Failed to install basic packages. Check your internet connection please."
+           reflector \
+           grep > /dev/null 2> /tmp/err || errorDialog "Failed to install basic packages. Check your internet connection please."
 
     installZSH
+}
+
+findBestMirrors () {
+    reflector --latest 200 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist > /dev/null 2> /tmp/err || errorDialog "Something got screwed up and we couldn't accomplish finding some fast and up-to-date servers :("
 }
 
 installYaourt () {
@@ -532,6 +537,28 @@ installYaourtStep () {
     setvar "install-yaourt-step" "done"
 }
 
+findBestMirrorsStep () {
+    getvar "find-best-mirrors-step"
+    if [ "$value" == "done" ]; then
+        return
+    fi
+
+    dialog --infobox "Looking for faster and more up-to-date mirrors for rest of the installation..." 6 50; findBestMirrors
+
+    setvar "find-best-mirrors-step"
+}
+
+installBasicPackagesStep () {
+    getvar "install-basic-packages-step"
+    if [ "$value" == "done" ]; then
+        return
+    fi
+
+    dialog --infobox "Installing some basic packages before creating users..." 5 50; installBasicPackages
+
+    setvar "install-basic-packages-step"
+}
+
 installPackagesStep () {
     getvar "install-packages-step"
     if [ "$value" == "done" ]; then
@@ -585,7 +612,8 @@ usersStep () {
   getvar "username"
   username=$value
 
-  dialog --infobox "Installing some basic packages before creating users..." 5 50; installBasicPackages
+  installBasicPackagesStep
+  findBestMirrorsStep
 
   createUser $username $password
 
