add timezone selector

diff --git a/dist/install b/dist/install
--- a/dist/install
+++ b/dist/install
@@ -8,6 +8,85 @@ setvar () {
 getvar () {
     value=$(grep "^$1=" ./install-vars | tail -n 1 | sed "s/^$1=//")
 }
+detectTimezone () {
+    if command_exists tzupdate ; then
+        dialog --infobox "Please wait, detecting your timezone... " 5 50; detected=$(tzupdate -p | sed "s/Detected timezone is //" | sed "s/\.//")
+        return
+    fi
+
+    detected=""
+}
+
+tzOptionsByRegion () {
+    options=$(cd /usr/share/zoneinfo/$1 && find . | sed "s|^\./||" | sed "s/^\.//" | sed '/^$/d')
+}
+
+tzRegions () {
+    regions=$(find /usr/share/zoneinfo/. -maxdepth 1 -type d | cut -d "/" -f6 | sed '/^$/d')
+}
+
+tzSelectionMenu () {
+    detectTimezone
+
+    if [[ -n "${detected// }" ]]; then
+        if [ -f "/usr/share/zoneinfo/$detected" ]; then
+           offset=$(TZ="$detected" date +%z | sed "s/00$/:00/g")
+
+           dialog --title "Timezones" \
+                  --backtitle "Happy Hacking Linux" \
+                  --yes-label "Yes, correct" \
+                  --no-label "No, I'll choose it" \
+                  --yesno "Your timezone was detected as $detected ($offset). Is it correct?" 7 50
+           selected=$?
+
+           if [ "$selected" = "0" ]; then
+               tzupdate > /dev/null
+           fi
+        fi
+    fi
+
+    tzRegions
+    regionsArray=()
+    while read name; do
+        regionsArray+=($name "")
+    done <<< "$regions"
+
+    region=$(dialog --stdout \
+                      --title "Timezones" \
+                      --backtitle "$1" \
+                      --ok-label "Next" \
+                      --no-cancel \
+                      --menu "Select a continent or ocean from the menu:" \
+                      20 30 30 \
+                      "${regionsArray[@]}")
+
+    tzOptionsByRegion $region
+
+    optionsArray=()
+    while read name; do
+        offset=$(TZ="$region/$name" date +%z | sed "s/00$/:00/g")
+        optionsArray+=($name "($offset)")
+    done <<< "$options"
+
+    tz=$(dialog --stdout \
+                    --title "Timezones" \
+                    --backtitle "$1" \
+                    --ok-label "Next" \
+                    --cancel-label "Back to Regions" \
+                    --menu "Select your timezone in ${region}:" \
+                    20 40 30 \
+                    "${optionsArray[@]}")
+
+    if [[ -z "${tz// }" ]]; then
+        tzSelectionMenu
+    else
+        selected="/usr/share/zoneinfo/$region/$tz"
+    fi
+}
+
+command_exists () {
+    type "$1" &> /dev/null ;
+}
 DISTRO_DL="https://git.io/vXbTE"
 
 init () {
@@ -53,7 +132,10 @@ installGRUB () {
 }
 
 localize () {
-    tzselect 2> /tmp/err || errorDialog "tzselect is missing"
+    yes | pip install tzupdate > /dev/null 2> /dev/null # ignore if it fails, let user choose tz
+
+    tzSelectionMenu "Happy Hacking Linux"
+
     hwclock --systohc
     sed -i -e '/^#en_US/s/^#//' /etc/locale.gen # uncomment lines starting with #en_US
     locale-gen 2> /tmp/err || errorDialog "locale-gen is missing"
@@ -160,6 +242,8 @@ installExtraPackages () {
            emacs \
            vim \
            htop \
+           python \
+           python-pip \
            go 2> /tmp/err || errorDialog "Failed to complete installing extra packages"
 }
 CHECK="[OK]"
