Switch to I3

diff --git a/dist/install b/dist/install
--- a/dist/install
+++ b/dist/install
@@ -175,10 +175,12 @@ linkDotFiles () {
     runuser -l $username -c "git clone $1 $target && cd $target && for file in .*; do cd /home/$username && rm -rf \$file && ln -s $target/\$file \$file; done" > /dev/null 2> /tmp/err || errorDialog "Can not install dotfiles at $1 :/"
 }
 
-installDefaultDotFiles () {
+installHappyDesktopConfig () {
     getvar "username"
     username=$value
-    runuser -l $username -c "git clone https://github.com/happy-hacking-linux/dotfiles.git /tmp/dotfiles && cp -rf /tmp/dotfiles/.* /home/$username/. && rm -rf ~/.git" > /dev/null 2> /tmp/err || errorDialog "Failed to install the default Happy Hacking dotfiles :/"
+    runuser -l $username -c "git clone https://github.com/happy-hacking-linux/happy-desktop.git /home/$username/.happy-desktop" > /dev/null 2> /tmp/err || errorDialog "Failed to clone the default desktop configuration. Please check your connection."
+    runuser -l $username -c "cd /home/$username/.config && ln -s /home/$username/.happy-desktop/config/* ." > /dev/null 2> /dev/null
+    runuser -l $username -c "cd /home/$username && ln -s /home/$username/.happy-desktop/dotfiles/* ." > /dev/null 2> /dev/null
 }
 
 installZSH () {
@@ -235,7 +237,18 @@ installBasicPackages () {
     installPkg "tlp"
     installPkg "unzip"
     installPkg "xf86-input-synaptics"
+    installPkg "bat"
+    installPkg "prettyping"
+    installPkg "fzf"
+    installPkg "tldr"
+    installPkg "ack"
+    installPkg "tmux"
     installZSH
+}
+
+installPrinterSupport () {
+    installPkg "cups"
+    installPkg "avahi"
 }
 
 upgrade () {
@@ -247,24 +260,33 @@ findBestMirrors () {
 }
 
 installYaourt () {
+    installAurPkg "yay"
     runAsUser "git clone https://aur.archlinux.org/package-query.git /tmp/package-query" > /dev/null 2> /tmp/err || errorDialog "Can not access Arch Linux repositories, check your internet connection."
     runAsUser "cd /tmp/package-query && yes | makepkg -si" > /dev/null 2> /tmp/err || errorDialog "Failed to build package-query."
     runAsUser "git clone https://aur.archlinux.org/yaourt.git /tmp/yaourt" > /dev/null 2> /tmp/err || errorDialog "Can not access Arch Linux repositories, check your internet connection."
     runAsUser "cd /tmp/yaourt && yes | makepkg -si" > /dev/null 2> /tmp/err || errorDialog "Failed to build Yaourt"
 }
 
-installXmonadDesktop () {
+installI3Desktop () {
     installPkg "xorg"
     installPkg "xorg-xinit"
-    installPkg "xmonad"
-    installPkg "xmonad-contrib"
-    installPkg "xmobar"
+    installPkg "compton"
+    installPkg "i3-gaps"
+    installPkg "i3status"
+    installPkg "i3lock"
+    installPkg "rofi"
     installPkg "feh"
     installPkg "unclutter"
     installPkg "scrot"
     installPkg "dmenu"
     installPkg "alsa-utils"
     installPkg "moc"
+    installPkg "slop"
+    installPkg "playerctl"
+    installPkg "libnotify"
+    installPkg "dunst"
+    installPkg "qalculate-gtk"
+    installAurPkg "polybar"
     installAurPkg "light-git"
 }
 
@@ -273,11 +295,13 @@ installXfce4Desktop () {
 }
 
 installFonts () {
-    installPkg "ttf-symbola"
     installPkg "ttf-dejavu"
+    installPkg "adobe-source-han-serif-otc-fonts"
+    installPkg "adobe-source-han-sans-otc-fonts"
     installAurPkg "ttf-monaco"
     installAurPkg "noto-fonts-emoji"
     installAurPkg "ttf-emojione-color"
+    installAurPkg "ttf-symbola"
 }
 
 installURXVT () {
@@ -515,7 +539,7 @@ errorDialog () {
 }
 
 installationProgress () {
-    total=50
+    total=70
     instcounter=$((instcounter+1))
     percent=$((100*$instcounter/$total))
 
@@ -570,11 +594,6 @@ installDotFilesStep () {
 
     if [[ -n "${dotFilesRepo// }" ]]; then
         dialog --infobox "Fingers crossed, we're linking your dotfiles into ~/" 5 50; linkDotFiles $dotFilesRepo
-
-        dotFilesBase=$(basename "$dotFilesRepo" | cut -f 1 -d '.')
-        if [ -f /home/$username/$dotFilesBase/post-install.sh ]; then
-            dialog --infobox "Running personal post-install commands, I hope we won't screw up anything" 5 50; runuser -l $username -c "sh /home/$username/$dotFilesBase/post-install.sh"
-        fi
     fi
 }
 
@@ -646,9 +665,9 @@ installPackagesStep () {
     installOhMyZSH
     installFonts
     installURXVT
-    installXmonadDesktop
-    dialog --infobox "Installing Default Configuration..." 5 50; installDefaultDotFiles
+    installI3Desktop
     installDotFilesStep
+    dialog --infobox "Configuring Happy Desktop..." 5 50; installHappyDesktopConfig
     installVirtualBoxStep
     installMacbookStep
     installBootStep
